version: '3.8'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: nextbuy-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: nextbuy-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      # Cấu hình quan trọng để App bên ngoài Docker (localhost) kết nối được
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  # Payment Service (Port 6007)
  # payment-service:
  #   build:
  #     context: .
  #     dockerfile: apps/payment-service/Dockerfile
  #   container_name: nextbuy-payment-service
  #   ports:
  #     - "6007:6007"
  #   environment:
  #     - PORT=6007
  #     - DATABASE_URL=${DATABASE_URL}
  #     - REDIS_URL=${REDIS_URL}
  #     - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
  #     - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
  #     - KAFKA_BROKERS=kafka:9092
  #   depends_on:
  #     - kafka
  